services:
  - type: web
    name: organizaai-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECURE
        value: "true"
      - key: CORS_ALLOWED_ORIGIN
        value: https://organizaai.vercel.app
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
